Attempt to make the sound driver recompile, at least for LINT which has the sscape/trix driver active, which (for some reason) disables the mpu401 driver, causing an undefined reference to mpuintr.  This was broken with rev 1.79 (part of the PC98 nss driver commit).